# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProgressBar(object):
    def setupUi(self, Form):
        Form.setObjectName("Progress Bar")
        Form.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 100))
        Form.setMaximumSize(QtCore.QSize(400, 100))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 21))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(10, 40, 381, 21))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Progress Bar", "Téléchargement..."))
        self.label.setText(_translate("Progress Bar", "Téléchargement..."))
        self.progressBar.setFormat(_translate("Progress Bar", "%p%"))

    def set_progress(self, value):
        self.progressBar.setValue(value)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_ProgressBar()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())